### PR TITLE
Add merge policy for the private repos

### PR DESCRIPTION
**Pull request by jaskeerat789**
# Description
We faced a bit confusion today while merging the latest PR. The merge policy for our private repos is not defined here but i was told that we follow `squash and merge` policy only. To avoid such confusion in future, I have mentioned this policy under `git` section of the readme file.

### CODE REVIEW

**Comment by MarioUhrik** [comment]
LGTM, though I'd prefer to apply both lines to both private & public repos
```
- we require rebase, fast-forward merge policy (`rebase + merge --ff-only`) on open-sourced repositories
- we require [squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits) policy on private repositories
```

**Comment by bernardhalas** [comment]
I agree with the above. Is there anything we should change in the README?

**Review by MarioUhrik — APPROVED** [review]
LGTM
@bernardhalas , please check & merge if you're ok with this

**Comment by bernardhalas** [comment]
hi folks. lines 40 and 41 are incompatible with each other. so should we or should we not do rebase on _all_ repositories?

**Comment by MarioUhrik** [comment]
Are they really incompatible? Perhaps I misunderstand, but I think both can be done.

Either way, what I truly care about deeply is only the `squash and merge` button when merging in the GUI.
I personally don't really care how (un)tidily the commits are arranged within the PR.
Also, I expect that there are no merge conflicts with the target branch, of course.

So, in short:
- I don't care if we remove this part:
```
we require rebase, fast-forward merge policy (`rebase + merge --ff-only`) on __all__ repositories
```
- I think this part should absolutely be there:
```
we require [squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits) policy on __all__ repositories
```

**Comment by bernardhalas** [comment]
yes, they are :)
pls, let's discuss here if we prefer rebase, 3-way merge, or we don't care. my preference would be the rebase for sure.

I agree with the squash itself absolutely.

**Comment by MarioUhrik** [comment]
Either way, I've pushed a new commit which simplifies and clarifies our intent.
Please review @jaskeerat789  @bernardhalas

**Comment by bernardhalas** [comment]
Hey @MarioUhrik ,

In order to progress towards a resolution here:
- Initially, these lines were not about the GitHub's workflow at all; I think it's OK to say we are using the GitHub's workflow(and it makes a complete sense); this is where most of our misalignment between the two of us came from.
- From the GitHub's workflows, I agree to move forward with `squash + merge` for all the reasons you stated.
- `rebase` would be important for having a linear history, which is something we don't really need here.

**Comment by MarioUhrik** [comment]
Agreed

**Pull request merged**
