### PR TITLE
Remove the golang doc

### PR DESCRIPTION
**Pull request by MarioUhrik**
We aren't truly using it nor maintaining it anymore.
It's just better to clean it up.
When selecting a golang coding guideline, we'll probably
refer to something on the Internet rather than making our own.

### CODE REVIEW

**Comment by bernardhalas** [comment]
LGTM, let's do that. Is there any coding guideline guys you follow? If so, could we reference it? @MiroslavRepka @Despire @jaskeerat789

**Review by bernardhalas — APPROVED** [review]

**Comment by MiroslavRepka** [comment]
I really like the uber go [guidelines](https://github.com/uber-go/guide).

**Comment by Despire** [comment]
I personally like [this](https://dave.cheney.net/practical-go/presentations/qcon-china.html)

**Comment by bernardhalas** [comment]
Please discuss internally and create a commit with the outcome.

**Comment by bernardhalas** [comment]
Hi @jaskeerat789 @MiroslavRepka @Despire , please kindly consider the next steps of this PR.

**Review by MiroslavRepka — APPROVED** [review]
LGTM, thanks for cleaning up the outdated doc

**Review by jaskeerat789 — APPROVED** [review]
LGTM, Thanks for the changes @MarioUhrik

**Pull request merged**
